// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgk8i_Jj3-qprTrZWXTPUaGb5BUG8fVt8',
    appId: '1:763593095313:ios:1c69b820e94cb85d2b2730',
    messagingSenderId: '763593095313',
    projectId: 'medapp-bilal-01',
    storageBucket: 'medapp-bilal-01.firebasestorage.app',
    iosBundleId: 'com.example.tangierMedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgk8i_Jj3-qprTrZWXTPUaGb5BUG8fVt8',
    appId: '1:763593095313:ios:1c69b820e94cb85d2b2730',
    messagingSenderId: '763593095313',
    projectId: 'medapp-bilal-01',
    storageBucket: 'medapp-bilal-01.firebasestorage.app',
    iosBundleId: 'com.example.tangierMedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdlUXdSQKJrBQ9Dl7rzeC9vAPmewmINQ',
    appId: '1:763593095313:web:194e1f6025b9d29d2b2730',
    messagingSenderId: '763593095313',
    projectId: 'medapp-bilal-01',
    authDomain: 'medapp-bilal-01.firebaseapp.com',
    storageBucket: 'medapp-bilal-01.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdlUXdSQKJrBQ9Dl7rzeC9vAPmewmINQ',
    appId: '1:763593095313:web:194e1f6025b9d29d2b2730',
    messagingSenderId: '763593095313',
    projectId: 'medapp-bilal-01',
    authDomain: 'medapp-bilal-01.firebaseapp.com',
    storageBucket: 'medapp-bilal-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJhLCDi_dSyVv99HZ2KF5_DKIec2AXJT8',
    appId: '1:763593095313:android:0f9e441176df43cd2b2730',
    messagingSenderId: '763593095313',
    projectId: 'medapp-bilal-01',
    storageBucket: 'medapp-bilal-01.firebasestorage.app',
  );
}